app/views/hosts.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, request, redirect, url_for, flash
from sqlalchemy import and_

import time
import simplejson as json

from app.models import *
from app.sunstone import Sunstone

mod = Blueprint('hosts', __name__, url_prefix='/hosts')


@mod.route('/', defaults={'page':1})
@mod.route('/page/<int:page>')
def index(page, **kvargs):
    hosts = Hosts.query.order_by(Hosts.hostname.asc()).paginate(page, per_page=15, error_out=True)
    return render_template('hosts/index.html', hosts=hosts)


@mod.route('/refresh')
def refresh():
    ts = int(time.time())
    for x in Cluster.query.all():
        sunstone = Sunstone(x)
        resp = sunstone.host()
        print resp.status
        info = json.loads(resp.data)['HOST_POOL']['HOST']
        if type(info) == dict:
            info = [info]
        for y in info:
            hostinst = Hosts.query.filter(and_(Hosts.cluster_id==x.id, Hosts.sunstone_id==y['ID'])).first()
            if hostinst:
                hostinst.vmnum      = y['HOST_SHARE']['RUNNING_VMS']
                hostinst.max_cpu    = y['HOST_SHARE']['MAX_CPU']
                hostinst.cpu_usage  = y['HOST_SHARE']['CPU_USAGE']
                hostinst.used_cpu   = y['HOST_SHARE']['USED_CPU']
                hostinst.max_mem    = y['HOST_SHARE']['MAX_MEM']
                hostinst.mem_usage  = y['HOST_SHARE']['MEM_USAGE']
                hostinst.used_mem   = y['HOST_SHARE']['USED_MEM']
            else:
                hostinst = Hosts(x.id, y['ID'], y['NAME'], y['HOST_SHARE']['RUNNING_VMS'], 
                                 y['HOST_SHARE']['MAX_CPU'], y['HOST_SHARE']['CPU_USAGE'], y['HOST_SHARE']['USED_CPU'], 
                                 y['HOST_SHARE']['MAX_MEM'], y['HOST_SHARE']['MEM_USAGE'], y['HOST_SHARE']['USED_MEM'], ts)
            db.session.add(hostinst)
            db.session.commit()
    newest_update = Hosts.query.order_by(Hosts.last_update_time.desc()).first()
    Hosts.query.filter(Hosts.last_update_time < newest_update.last_update_time).delete()
    return redirect(url_for('.index'))

app/views/order.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask.ext.wtf import Form, SelectField, TextField, BooleanField, Required, Length
from flask.ext.login import current_user
from flask.ext.paginate import Pagination

from sqlalchemy import distinct

import simplejson as json

from app import app
from app.models import *
from app.dicts import *
from app.views import *
from app.occi import OCCI
from app.order import *
from app.vm import VMC

mod = Blueprint('order', __name__, url_prefix='/order')


@mod.route('/new', methods=['GET', 'POST'])
def new():
    form = OrderForm()
    form.cluster_id.choices = [(i.id, i.name) for i in Cluster.query.all()]
    form.cnt.choices = [(i, i) for i in range(1, 11)]
    cpu = db.session.query(CPU_Mem.cpu.distinct().label('cpu')).order_by(CPU_Mem.cpu).all()

    if not form.validate_on_submit():
        edit = 1 if request.method=='POST' else 0
        return render_template('order/new.html', form=form, cpu=cpu, edit=edit, price=app.config['PRICE'])

    orders = Orders(form.cluster_id.data, form.cpu.data, form.mem.data, form.network.data, form.disk.data, 
                    request.form['os_id'], form.cnt.data, 0, current_user.user_id, form.desc.data, form.days.data)
    db.session.add(orders)
    db.session.commit()

    return redirect(url_for('my_order.list'))


@mod.route('/list', defaults={'page':1})
@mod.route('/list/page/<int:page>')
def list(page, **kvargs):
    order = Orders.query.order_by(Orders.id.desc()).paginate(page, per_page=15, error_out=True)
    return render_template('order/list.html', order=order, order_status=app.config['ORDER_STATUS'])


@mod.route('/<int:order_id>/view')
@check_load_order
def view(order, **kvargs):
    network_dict = network2dict()
    form = OrderForm(obj=order)
    return render_template('order/view.html', order=order, network_dict=network_dict, form=form, config=app.config)


@mod.route('/<int:order_id>/edit', methods=['GET', 'POST'])
@check_load_order
def edit(order, **kvargs):
    order.disk = ','.join(str(x) for x in order.disk)
    order.network = ','.join(str(x) for x in order.network)
    cpu = db.session.query(CPU_Mem.cpu.distinct().label('cpu')).order_by(CPU_Mem.cpu).all()
    form = OrderForm(obj=order)
    form.cluster_id.choices = [(i.id, i.name) for i in Cluster.query.all()]
    form.cnt.choices = [(i, i) for i in range(1, 11)]

    if not form.validate_on_submit():
        return render_template('order/edit.html', form=form, cpu=cpu, order=order, edit=1, price=app.config['PRICE'])

    form.populate_obj(order)
    db.session.add(order)
    db.session.commit()

    return redirect(url_for('my_order.view', order_id=order.id))


@mod.route('/<int:order_id>/delete', methods=['GET', 'POST'])
@check_load_order
def delete(order, **kvargs):
    ret = {}
    vmc = VMC()

    try:
        for x in order.vm:
            vmc.delete(x)
        db.session.delete(order)
        db.session.commit()
        ret['status'] = 1
        ret['msg'] = u"删除成功"
    except:
        ret['status'] = 0
        ret['msg'] = u"删除失败"

    return json.dumps(ret)


@mod.route('/<int:order_id>/approve')
@check_load_order
def approve(order, **kvargs):
    orderc = OrderC(order)
    if orderc.create_vm():
        flash(u'虚拟机创建成功', 'success')
    else:
        flash(u'虚拟机创建失败', 'error')
    return redirect(url_for('.view', order_id=order.id))


@mod.route('/<int:order_id>/cancle')
@check_load_order
def cancle(order, **kvargs):
    orderc = OrderC(order)
    orderc.cancle()
    flash(u'取消申请', '')
    return redirect(request.referrer)


@mod.route('/<int:order_id>/reject')
@check_load_order
def reject(order, **kvargs):
    orderc = OrderC(order)
    orderc.reject()
    return redirect(url_for('.view', order_id=order.id))


@mod.route('/<int:order_id>/refresh')
@check_load_order
def refresh(order, **kvargs):
    vminst = VMC()
    if vminst.refresh():
        flash(u'刷新成功', 'success')
    else:
        flash(u'刷新失败', 'success')
    return redirect(request.referrer)


@mod.route('/<int:order_id>/state_change')
@check_load_order
def state_change(order, **kvargs):
    new_state = request.args.get('state', order.status)
    order.status = new_state
    db.session.add(order)
    db.session.commit()
    return redirect(url_for('.view', order_id=order.id))


class OrderForm(Form):
    desc = TextField(u'用途', validators=[Required(message=u"不能为空")])
    cluster_id = SelectField(u'集群', coerce=int)
    cpu = TextField(u'CPU', validators=[Required()])
    mem = TextField(u'内存', validators=[Required()])
    network = TextField(u'网络', validators=[])
    disk = TextField(u'磁盘', validators=[])
    os_id = TextField(u'操作系统', validators=[Required()])
    cnt = SelectField(u'台数', coerce=int)
    days = TextField(u'天数', validators=[Length(max=30)])

app/views/vm.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, request, redirect, url_for, make_response, jsonify, flash

import simplejson as json

from app import app, db
from app.views import *
from app.utils import *
from app.dicts import *
from app.models import *
from app.vm import VMC
from app.sunstone import Sunstone

mod = Blueprint('vm', __name__, url_prefix='/vm')


@mod.route('/test', defaults={'page':1})
@mod.route('/test/page/<int:page>')
def test(page, **kvargs):
    vms = VM.query.filter(VM.if_test==1).order_by(VM.hostname.asc()).paginate(page, per_page=15, error_out=True)
    return render_template('vm/test.html', vms=vms)


@mod.route('/production', defaults={'page':1})
@mod.route('/production/page/<int:page>')
def production(page, **kvargs):
    vms = VM.query.filter(VM.if_test!=1).order_by(VM.hostname.asc()).paginate(page, per_page=15, error_out=True)
    return render_template('vm/production.html', vms=vms)


@mod.route('/<int:vm_id>/view')
@check_load_vm
def view(vm, **kvargs):
    vminst = VMC()
    vm_detail = vminst.detail(vm)
    network_dict = network2dict()
    cpu = [x.cpu for x in db.session.query(CPU_Mem.cpu.distinct().label('cpu')).order_by(CPU_Mem.cpu).all()]
    mem = CPU_Mem.query.filter(CPU_Mem.cpu==vm.cpu).order_by(CPU_Mem.mem).all()
    return render_template('vm/view.html', vm=vm, cpu=cpu, mem=mem, vm_detail=vm_detail, network_dict=network_dict)


@mod.route('/<int:vm_id>/delete', methods=['POST'])
@check_load_vm
def delete(vm, **kvargs):
    vminst = VMC()
    status = 1 if vminst.delete(vm) else 0
    return jsonify(status=status)


@mod.route('/action', methods=['POST'])
def action_mult():
    status = 1
    vminst = VMC()

    try:
        action = request.form['action']
    except:
        action = None

    if request.form['vmlist'] == "":
        vmlist = []
    else:
        vmlist = request.form['vmlist'].split(',')

    for x in vmlist:
        vm = VM.query.get(int(x))
        if action == 'delete':
            if not vminst.delete(vm):
                status = 0
        if action == 'start':
            if not vminst.start(vm):
                status = 0
        if action == 'poweroff':
            if not vminst.poweroff(vm):
                status = 0
        if action == 'poweroff_hard':
            if not vminst.poweroff_hard(vm):
                status = 0
        if action == 'reboot':
            if not vminst.reboot(vm):
                status = 0
        if action == 'reboot_hard':
            if not vminst.reboot_hard(vm):
                status = 0
        if action == 'recreate':
            if not vminst.recreate(vm):
                status = 0

    vminst.refresh()

    if status:
        flash(u'操作成功', 'success')
    else:
        flash(u'操作失败', 'error')
    return redirect(request.referrer)


@mod.route('/<int:vm_id>/rename', methods=['GET', 'POST'])
@check_load_vm
def rename(vm, **kvargs):
    try:
        newname = request.form['data'] or vm.hostname
        vminst = VMC()
        vminst.rename(vm, newname)
        vm.hostname = newname
        db.session.add(vm)
        db.session.commit()
        status = 1
    except:
        status = 0

    return jsonify(status=status)


@mod.route('/<int:vm_id>/resize', methods=['GET', 'POST'])
@check_load_vm
def resize(vm, **kvargs):
    try:
        vminst = VMC()
        cpu = request.form['cpu'] or vm.cpu
        mem = request.form['mem'] or vm.mem
        vminst.resize(vm, cpu, mem)
        status = 1
    except:
        status = 0

    return jsonify(status=status)


@mod.route('/<int:vm_id>/attach_nic', methods=['GET', 'POST'])
@check_load_vm
def attach_nic(vm, **kvargs):
    #try:
    vminst = VMC()
    network_id = request.form['network_id']
    vminst.attach_nic(vm, network_id)
    flag = True
    sunstone = Sunstone(vm.cluster)
    while flag:
        resp = sunstone.vm_id(vm.vm_id)
        info = json.loads(resp.data)['VM']
        if int(info['STATE']) == 3:
            flag = False
    status = 1
    #except:
    #    status = 0

    return jsonify(status=status)


@mod.route('/<int:vm_id>/detach_nic', methods=['GET', 'POST'])
@check_load_vm
def detach_nic(vm, **kvargs):
    try:
        vminst = VMC()
        nic_id = request.form['nic_id']
        vminst.detach_nic(vm, nic_id)
        flag = True
        sunstone = Sunstone(vm.cluster)
        while flag:
            resp = sunstone.vm_id(vm.vm_id)
            info = json.loads(resp.data)['VM']
            if int(info['STATE']) == 3:
                flag = False
        status = 1
    except:
        status = 0

    return jsonify(status=status)


@mod.route('/<int:vm_id>/redesc', methods=['GET', 'POST'])
@check_load_vm
def redesc(vm, **kvargs):
    try:
        desc = request.form['data'] or vm.desc
        vm.desc = desc
        db.session.add(vm)
        db.session.commit()
        status = 1
    except:
        status = 0

    return jsonify(status=status)


@mod.route('/refresh')
def refresh():
    vminst = VMC()
    if vminst.refresh():
        flash(u'刷新成功', 'success')
    else:
        flash(u'刷新失败', 'error')
    return redirect(request.referrer)

app/templates/import/forms.html
{% macro error(msg, class='') %}
    {% if msg %}
    <span class="{{ class }} help-inline label label-important">
        {{ msg[0] }}
    </span>
    {% endif %}
{% endmacro %}


{% macro field(form, name, eclass='', gclass='', autocomplete='') %}
<div class="control-group {{ gclass }}">
    {{ form[name].label(class="control-label") }}
    <div class="controls">
        {% if(autocomplete!='') %}
            {{ form[name](class=eclass, autocomplete=autocomplete) }}
        {% else %}
            {{ form[name](class=eclass) }}
        {% endif %}
        {{ error(form.errors[name]) }}
    </div>
</div>
{% endmacro %}


{% macro field_form(form, name) %}
<div class="control-group">
    {{ form[name].label(class="control-label") }}
    <div class="controls pdt-5">
        {{ form[name] }}
    </div>
</div>
{% endmacro %}


{% macro field_disp(label, value) %}
<div class="control-group">
    <label class="control-label">{{ label }}</label>
    <div class="controls pdt-5">
        {{ value }}
    </div>
</div>
{% endmacro %}


{% macro cluster_form(form, legend, url, submit, cancle_url) %}
<form class="form-horizontal" action="{{ url }}" method="POST">
    <legend>{{ legend }}</legend>

    {{ form.hidden_tag() }}
    {{ form.csrf }}

    {{ field(form, 'idc_id') }}
    {{ field(form, 'name') }}
    {{ field(form, 'if_test') }}
    {{ field(form, 'host') }}
    {{ field(form, 'occi_api') }}
    {{ field(form, 'occi_auth') }}
    {{ field(form, 'sunstone_api') }}
    {{ field(form, 'sunstone_auth') }}
    {{ field(form, 'ds_id', gclass='hide') }}
    {{ field(form, 'ds_name', autocomplete='off') }}

    <div class="form-actions">
        <button type="submit" class="btn btn-primary">{{ submit }}</button>
        <a class="btn" href="{{ cancle_url }}">取消</a>
    </div>
</form>
{% endmacro %}

app/templates/import/nav.html
{% macro nav(current_user, view) %}
<script>
$(document).ready(function() {
    $(".{{view}}").addClass("active");
});
</script>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="{{ url_for('index') }}">Anjuke Private Cloud</a>
            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li class="buy" id="nav_buy"><a href="{{ url_for('order.new') }}">购买</a></li>
                    <li class="order_list" id="nav_order_list"><a href="{{ url_for('order.list') }}">订单</a></li>
                    <li class="dropdown machine">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">机器&nbsp;<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="hosts"><a href="{{ url_for('hosts.index') }}">宿主机</a></li>
                            <li class="divider"></li>
                            <li class="nav-header">虚拟机</li>
                            <li class="vm_test"><a href="{{ url_for('vm.test') }}">测试机</a></li>
                            <li class="vm_production"><a href="{{ url_for('vm.production') }}">线上机器</a></li>
                        </ul>
                    <li>
                </ul>
                <ul class="nav pull-right">
                    {% if current_user.is_authenticated() %}
                    <li class="my"><a href="{{ url_for('my_vm.test') }}">个人中心</a></li>
                    {% if current_user.role == 1 %}
                    <li class="admin"><a href="{{ url_for('admin.index') }}">管理</a></li>
                    {% endif %}
                    <li><a href="#">您好，{{ current_user.chinese_name }}！</a></li>
                    <li><a href="{{ url_for('logout') }}">注销</a></li>
                    {% else %}
                    <li><a href="{{ url_for('login') }}">登录</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endmacro %}

app/templates/import/nav_admin.html
{% macro nav_admin(view) %}
<script type="text/javascript">
$(document).ready(function() {
    $("#nav_{{ view }}").addClass("active");
});
</script>

<div class="block">
    <h2>基础设施</h2>
    <ul>
        <li id="nav_idc"><a href="{{ url_for('idc.index') }}">IDC</a></li>
        <li id="nav_cluster"><a href="{{ url_for('cluster.index') }}">Cluster</a></li>
        <li id="nav_cpu_mem"><a href="{{ url_for('cpu_mem.index') }}">CPU/Memory</a></li>
        <li id="nav_network"><a href="{{ url_for('network.index') }}">网络</a></li>
        <li id="nav_osimage"><a href="{{ url_for('osimage.index') }}">OS镜像</a></li>
    </ul>
</div>

<div class="block">
    <h2>用户</h2>
    <ul>
        <li><a href="#">用户列表</a></li>
    </ul>
</div>

<div class="block">
    <h2>其他</h2>
    <ul>
        <li><a href="#">其他</a></li>
    </ul>
</div>
{% endmacro %}

app/templates/import/nav_my.html
{% macro nav_my(view) %}
<script type="text/javascript">
$(document).ready(function() {
    $("#nav_{{ view }}").addClass("active");
});
</script>

<div class="block">
    <h2>账户</h2>
    <ul>
        <li id="nav_my_order"><a href="{{ url_for('my_order.list') }}">我的订单</a></li>
        <li><a href="#">消费历史</a></li>
        <li><a href="">资源变更</a></li>
    </ul>
</div>

<div class="block">
    <h2>机器列表</h2>
    <ul>
        <li><a href="{{ url_for('my_vm.test') }}">测试机</a></li>
        <li><a href="{{ url_for('my_vm.production') }}">线上机器</a></li>
    </ul>
</div>

<div class="block">
    <h2>其他</h2>
    <ul>
        <li><a href="#">个人信息</a></li>
    </ul>
</div>
{% endmacro %}

app/templates/import/pagination.html
{% macro render_pagination(pagination, endpoint) %}
<div class="pagination text-center">
    <div class="pull-left">
        共<b>{{ pagination.total }}</b>条记录，
        当前第<b>
        {% if pagination.items.__len__() == 0 %}
            0
        {% else %}
            {{ (pagination.page-1)*pagination.per_page + 1 }}
        {% endif %}
        - {{ (pagination.page-1)*pagination.per_page + pagination.items.__len__() }}</b>条
    </div>
    <ul class="pull-right">
        {% if pagination.pages == 0 %}
            <li class="disabled"><a href="#">First</a></li>
        {% else %}
            {% if pagination.page == 1 %}
                <li class="active"><a href="#">First</a></li>
            {% else %}
                <li><a href="{{ url_for(endpoint, page=1) }}">First</a></li>
            {% endif %}
        {% endif %}

        {% if pagination.has_prev %}
            <li><a href="{{ url_for(endpoint, page=pagination.prev_num) }}">&laquo;</a></li>
        {% else %}
            <li class="disabled"><a href="#">&laquo;</a></li>
        {% endif %}

        {% for page in pagination.iter_pages() %}
        {% if page %}
            {% if page != pagination.page %}
                <li><a href="{{ url_for(endpoint, page=page) }}">{{ page }}</a></li>
            {% else %}
                <li class="active"><a href="#">{{ page }}</a></li>
            {% endif %}
        {% else %}
            <li><span class=ellipsis>…</span></li>
        {% endif %}
        {% endfor %}

        {% if pagination.has_next %}
            <li><a href="{{ url_for(endpoint, page=pagination.next_num) }}">&raquo;</a></li>
        {% else %}
            <li class="disabled"><a href="#">&raquo;</a></li>
        {% endif %}

        {% if pagination.pages == 0 %}
            <li class="disabled"><a href="#">Last</a></li>
        {% else %}
            {% if pagination.page == pagination.pages %}
                <li class="active"><a href="#">Last</a></li>
            {% else %}
                <li><a href="{{ url_for(endpoint, page=pagination.pages) }}">Last</a></li>
            {% endif %}
        {% endif %}
    </ul>
    <div class="clear"></div>
</div>
{% endmacro %}