app/views/order.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask.ext.wtf import Form, SelectField, TextField, BooleanField, Required, Length
from flask.ext.login import current_user
from flask.ext.paginate import Pagination

from sqlalchemy import distinct

import simplejson as json

from app import app
from app.models import *
from app.dicts import *
from app.views import *
from app.occi import OCCI
from app.order import *
from app.vm import VMC

mod = Blueprint('order', __name__, url_prefix='/order')


@mod.route('/new', methods=['GET', 'POST'])
def new():
    form = OrderForm()
    form.cluster_id.choices = [(i.id, i.name) for i in Cluster.query.all()]
    form.cnt.choices = [(i, i) for i in range(1, 11)]
    cpu = db.session.query(CPU_Mem.cpu.distinct().label('cpu')).order_by(CPU_Mem.cpu).all()

    if not form.validate_on_submit():
        edit = 1 if request.method=='POST' else 0
        return render_template('order/new.html', form=form, cpu=cpu, edit=edit, price=app.config['PRICE'])

    orders = Orders(form.cluster_id.data, form.cpu.data, form.mem.data, form.network.data, form.disk.data, 
                    request.form['os_id'], form.cnt.data, 0, current_user.user_id, form.desc.data, form.days.data)
    db.session.add(orders)
    db.session.commit()

    return redirect(url_for('my_order.list'))


@mod.route('/list', defaults={'page':1})
@mod.route('/list/page/<int:page>')
def list(page, **kvargs):
    order = Orders.query.order_by(Orders.id.desc()).paginate(page, per_page=15, error_out=True)
    return render_template('order/list.html', order=order, order_status=app.config['ORDER_STATUS'])


@mod.route('/<int:order_id>/view')
@check_load_order
def view(order, **kvargs):
    network_dict = network2dict()
    form = OrderForm(obj=order)
    return render_template('order/view.html', order=order, network_dict=network_dict, form=form, config=app.config)


@mod.route('/<int:order_id>/edit', methods=['GET', 'POST'])
@check_load_order
def edit(order, **kvargs):
    order.disk = ','.join(str(x) for x in order.disk)
    order.network = ','.join(str(x) for x in order.network)
    cpu = db.session.query(CPU_Mem.cpu.distinct().label('cpu')).order_by(CPU_Mem.cpu).all()
    form = OrderForm(obj=order)
    form.cluster_id.choices = [(i.id, i.name) for i in Cluster.query.all()]
    form.cnt.choices = [(i, i) for i in range(1, 11)]

    if not form.validate_on_submit():
        return render_template('order/edit.html', form=form, cpu=cpu, order=order, edit=1, price=app.config['PRICE'])

    form.populate_obj(order)
    db.session.add(order)
    db.session.commit()

    return redirect(url_for('my_order.view', order_id=order.id))


@mod.route('/<int:order_id>/delete', methods=['GET', 'POST'])
@check_load_order
def delete(order, **kvargs):
    ret = {}
    vmc = VMC()

    try:
        for x in order.vm:
            vmc.delete(x)
        db.session.delete(order)
        db.session.commit()
        ret['status'] = 1
        ret['msg'] = u"删除成功"
    except:
        ret['status'] = 0
        ret['msg'] = u"删除失败"

    return json.dumps(ret)


@mod.route('/<int:order_id>/approve')
@check_load_order
def approve(order, **kvargs):
    orderc = OrderC(order)
    if orderc.create_vm():
        flash(u'虚拟机创建成功', 'success')
    else:
        flash(u'虚拟机创建失败', 'error')
    return redirect(url_for('.view', order_id=order.id))


@mod.route('/<int:order_id>/cancle')
@check_load_order
def cancle(order, **kvargs):
    orderc = OrderC(order)
    orderc.cancle()
    flash(u'取消申请', '')
    return redirect(request.referrer)


@mod.route('/<int:order_id>/reject')
@check_load_order
def reject(order, **kvargs):
    orderc = OrderC(order)
    orderc.reject()
    return redirect(url_for('.view', order_id=order.id))


@mod.route('/<int:order_id>/refresh')
@check_load_order
def refresh(order, **kvargs):
    vminst = VMC()
    if vminst.refresh():
        flash(u'刷新成功', 'success')
    else:
        flash(u'刷新失败', 'success')
    return redirect(request.referrer)


@mod.route('/<int:order_id>/state_change')
@check_load_order
def state_change(order, **kvargs):
    new_state = request.args.get('state', order.status)
    order.status = new_state
    db.session.add(order)
    db.session.commit()
    return redirect(url_for('.view', order_id=order.id))


class OrderForm(Form):
    desc = TextField(u'用途', validators=[Required(message=u"不能为空")])
    cluster_id = SelectField(u'集群', coerce=int)
    cpu = TextField(u'CPU', validators=[Required()])
    mem = TextField(u'内存', validators=[Required()])
    network = TextField(u'网络', validators=[])
    disk = TextField(u'磁盘', validators=[])
    os_id = TextField(u'操作系统', validators=[Required()])
    cnt = SelectField(u'台数', coerce=int)
    days = TextField(u'天数', validators=[Length(max=30)])

app/views/vm.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, request, redirect, url_for, make_response, jsonify, flash

import simplejson as json

from app import app, db
from app.views import *
from app.utils import *
from app.dicts import *
from app.models import *
from app.vm import VMC
from app.sunstone import Sunstone

mod = Blueprint('vm', __name__, url_prefix='/vm')


@mod.route('/test', defaults={'page':1})
@mod.route('/test/page/<int:page>')
def test(page, **kvargs):
    vms = VM.query.filter(VM.if_test==1).order_by(VM.hostname.asc()).paginate(page, per_page=15, error_out=True)
    return render_template('vm/test.html', vms=vms)


@mod.route('/production', defaults={'page':1})
@mod.route('/production/page/<int:page>')
def production(page, **kvargs):
    vms = VM.query.filter(VM.if_test!=1).order_by(VM.hostname.asc()).paginate(page, per_page=15, error_out=True)
    return render_template('vm/production.html', vms=vms)


@mod.route('/<int:vm_id>/view')
@check_load_vm
def view(vm, **kvargs):
    vminst = VMC()
    vm_detail = vminst.detail(vm)
    network_dict = network2dict()
    cpu = [x.cpu for x in db.session.query(CPU_Mem.cpu.distinct().label('cpu')).order_by(CPU_Mem.cpu).all()]
    mem = CPU_Mem.query.filter(CPU_Mem.cpu==vm.cpu).order_by(CPU_Mem.mem).all()
    return render_template('vm/view.html', vm=vm, cpu=cpu, mem=mem, vm_detail=vm_detail, network_dict=network_dict)


@mod.route('/<int:vm_id>/delete', methods=['POST'])
@check_load_vm
def delete(vm, **kvargs):
    vminst = VMC()
    status = 1 if vminst.delete(vm) else 0
    return jsonify(status=status)


@mod.route('/action', methods=['POST'])
def action_mult():
    status = 1
    vminst = VMC()

    try:
        action = request.form['action']
    except:
        action = None

    if request.form['vmlist'] == "":
        vmlist = []
    else:
        vmlist = request.form['vmlist'].split(',')

    for x in vmlist:
        vm = VM.query.get(int(x))
        if action == 'delete':
            if not vminst.delete(vm):
                status = 0
        if action == 'start':
            if not vminst.start(vm):
                status = 0
        if action == 'poweroff':
            if not vminst.poweroff(vm):
                status = 0
        if action == 'poweroff_hard':
            if not vminst.poweroff_hard(vm):
                status = 0
        if action == 'reboot':
            if not vminst.reboot(vm):
                status = 0
        if action == 'reboot_hard':
            if not vminst.reboot_hard(vm):
                status = 0
        if action == 'recreate':
            if not vminst.recreate(vm):
                status = 0

    vminst.refresh()

    if status:
        flash(u'操作成功', 'success')
    else:
        flash(u'操作失败', 'error')
    return redirect(request.referrer)


@mod.route('/<int:vm_id>/rename', methods=['GET', 'POST'])
@check_load_vm
def rename(vm, **kvargs):
    try:
        newname = request.form['data'] or vm.hostname
        vminst = VMC()
        vminst.rename(vm, newname)
        vm.hostname = newname
        db.session.add(vm)
        db.session.commit()
        status = 1
    except:
        status = 0

    return jsonify(status=status)


@mod.route('/<int:vm_id>/resize', methods=['GET', 'POST'])
@check_load_vm
def resize(vm, **kvargs):
    try:
        vminst = VMC()
        cpu = request.form['cpu'] or vm.cpu
        mem = request.form['mem'] or vm.mem
        vminst.resize(vm, cpu, mem)
        status = 1
    except:
        status = 0

    return jsonify(status=status)


@mod.route('/<int:vm_id>/attach_nic', methods=['GET', 'POST'])
@check_load_vm
def attach_nic(vm, **kvargs):
    #try:
    vminst = VMC()
    network_id = request.form['network_id']
    vminst.attach_nic(vm, network_id)
    flag = True
    sunstone = Sunstone(vm.cluster)
    while flag:
        resp = sunstone.vm_id(vm.vm_id)
        info = json.loads(resp.data)['VM']
        if int(info['STATE']) == 3:
            flag = False
    status = 1
    #except:
    #    status = 0

    return jsonify(status=status)


@mod.route('/<int:vm_id>/detach_nic', methods=['GET', 'POST'])
@check_load_vm
def detach_nic(vm, **kvargs):
    try:
        vminst = VMC()
        nic_id = request.form['nic_id']
        vminst.detach_nic(vm, nic_id)
        flag = True
        sunstone = Sunstone(vm.cluster)
        while flag:
            resp = sunstone.vm_id(vm.vm_id)
            info = json.loads(resp.data)['VM']
            if int(info['STATE']) == 3:
                flag = False
        status = 1
    except:
        status = 0

    return jsonify(status=status)


@mod.route('/<int:vm_id>/redesc', methods=['GET', 'POST'])
@check_load_vm
def redesc(vm, **kvargs):
    try:
        desc = request.form['data'] or vm.desc
        vm.desc = desc
        db.session.add(vm)
        db.session.commit()
        status = 1
    except:
        status = 0

    return jsonify(status=status)


@mod.route('/refresh')
def refresh():
    vminst = VMC()
    if vminst.refresh():
        flash(u'刷新成功', 'success')
    else:
        flash(u'刷新失败', 'error')
    return redirect(request.referrer)

app/templates/order/import/view.html
{% macro order_view(order, network_dict, form, config, current_user, personal=False) %}
<div class="content-head">
    <h2 class="pull-left">订单详情</h2>
    <div class="pull-right">
      {% if personal %}
        <a href="{{ url_for('my_order.list') }}" title="返回" class="btn btn-action"><i class="icon-arrow-left"></i></a>
      {% else %}
        <a href="{{ url_for('order.list') }}" title="返回" class="btn btn-action"><i class="icon-arrow-left"></i></a>
      {% endif %}
      {% if order.status == 1 or order.status == 2 %}
        <a href="{{ url_for('vm.refresh') }}" title="刷新" class="btn btn-action"><i class="icon-refresh"></i></a>
      {% endif %}
      {% if order.status == 0 and current_user.role == 1 %}
        <div class="btn-group">
            <a href="{{ url_for('order.approve', order_id=order.id) }}" title="通过" class="btn btn-action"><i class="icon-ok"></i></a>
            <a href="{{ url_for('order.reject', order_id=order.id) }}" title="驳回" class="btn btn-action"><i class="icon-ban-circle"></i></a>
        </div>
      {% endif %}
      {% if order.status == 2 and current_user.role == 1 %}
        <a href="{{ url_for('order.approve', order_id=order.id) }}" title="重新创建" class="btn btn-action"><i class="icon-repeat"></i></a>
      {% endif %}
      {% if order.status == 0 %}
        <a href="{{ url_for('order.edit', order_id=order.id) }}" title="修改" class="btn btn-action"><i class="icon-edit"></i></a>
        <a href="{{ url_for('order.cancle', order_id=order.id) }}" title="取消" class="btn btn-action"><i class="icon-remove"></i></a>
      {% endif %}
    </div>
    <div class="clear"></div>
</div>

<div class="row-fluid">
    <div class="span8">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th width="30%">机器名</th>
                    <th width="40%">IP</th>
                    <th width="20%">状态</th>
                    <th width="10%">操作</th>
                </tr>
            </thead>
            <tbody>
                {% if order.vm.__len__() == 0 %}
                <tr>
                    <td colspan="4">Null</td>
                </tr>
                {% endif %}
                {% for v in order.vm %}
                <tr id="vm_{{ v.id }}">
                    <td>
                        <span class="hostname">{{ v.hostname }}</span>
                        <input value="{{ v.hostname }}" class="input-small hide hostname"/>
                    </td>
                    <td>{{ ','.join(v.ip) }}</td>
                    <td>{{ v.status }}</td>
                    <td class="action" data-trid="vm_{{ v.id }}">
                        <a class="edit" href="#"><i class="icon-edit"></i></a>
                        <a class="remove" href="{{ url_for('vm.delete', vm_id=v.id) }}"><i class="icon-remove"></i></a>
                        <a class="save hide" href="{{ url_for('vm.rename', vm_id=v.id) }}"><i class="icon-ok"></i></a>
                        <a class="cancle hide" href="#"><i class="icon-ban-circle"></i></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <h4>评论</h4>
        <p>To do...</p>
    </div>

    <div class="span4">
        <table width="100%" class="table table-bordered detail">
            <tr>
                <td width="30%" class="name">{{ form['desc'].label }}</td>
                <td width="70%">{{ order.desc }}</td>
            </tr>
            <tr>
                <td class="name">{{ form['cluster_id'].label }}</td>
                <td>{{ order.cluster.name }}</td>
            </tr>
            <tr>
                <td class="name">{{ form['cpu'].label }}</td>
                <td>{{ order.cpu }}核</td>
            </tr>
            <tr>
                <td class="name">{{ form['mem'].label }}</td>
                <td>{{ order.mem }}G</td>
            </tr>
            <tr>
                <td class="name">{{ form['os_id'].label }} </td>
                <td>{{ order.os.name }} </td>
            </tr>
            <tr>
                <td class="name">{{ form['network'].label }} </td>
                <td>
                {% if order.network[0] != '' %}
                {% for n in order.network %}
                    <span class="label">{{ network_dict[n].name }}</span>
                {% endfor %}
                {% endif %}
                </td>
            </tr>
            <tr>
                <td class="name">{{ form['disk'].label }}</td>
                <td>
                {% if order.disk[0] != '' %}
                {% for d in order.disk %}
                    <span class="label">{{ d }}G</span>
                {% endfor %}
                {% endif %}
                </td>
            </tr>
            <tr>
                <td class="name">{{ form['cnt'].label }}</td>
                <td>{{ order.cnt }}</td>
            </tr>
            <tr>
                <td class="name">状态</td>
                <td id="order-state">
                    <span class="label {{ config['ORDER_STATUS'][order.status]['class'] }}">
                        {{ config['ORDER_STATUS'][order.status]['label'] }}
                    </span>
                    {% if current_user.role == 1 %}
                    <a class="edit" href="#"><i class="icon-edit"></i></a>
                    <select class="input-small hide">
                        {% for x in config['ORDER_STATUS'].keys() %}
                        <option value="{{ x }}" 
                        {% if order.status == x %}
                            selected
                        {% endif %}
                        >{{ config['ORDER_STATUS'][x]['label'] }}</option>
                        {% endfor %}
                    </select>
                    <a class="cancle hide" href="#"><i class="icon-ban-circle"></i></a>
                    <a class="save hide" href="#" data-api="{{ url_for('order.state_change', order_id=order.id) }}"><i class="icon-ok"></i></a>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td class="name">申请时间</td>
                <td>{{ order.created_time.strftime("%Y-%m-%d %H:%M") }}</td>
            </tr>
            {% if not personal %}
            <tr>
                <td class="name">申请人</td>
                <td>{{ order.user.chinese_name }}</td>
            </tr>
            {% endif %}
        </table>
    </div>
</div>
{% endmacro %}