app/views/api.py
# -*- coding: utf-8 -*-

from flask import Blueprint, request

import simplejson as json

from app.models import *
from app.views import *

mod = Blueprint('api', __name__, url_prefix='/api')


@mod.route('/cluster/<int:cluster_id>')
@check_load_cluster
def cluster(cluster, **kvargs):
    return '{"cluster_id":%s , "cluster_name":"%s", "if_test":%s}' % \
            (cluster.id, cluster.name, cluster.if_test)


@mod.route('/cpu_scheme')
def cpu_scheme():
    ret = []

    for c in db.session.query(CPU_Mem.cpu.distinct().label('cpu')).order_by(CPU_Mem.cpu).all():
        ret.append(c.cpu)

    return json.dumps(ret)


@mod.route('/mem_scheme')
def mem_scheme():
    ret = []
    cpu = request.args.get('cpu')

    for m in CPU_Mem.query.filter_by(cpu=cpu).order_by(CPU_Mem.mem):
        ret.append(m.mem)

    return json.dumps(ret)


@mod.route('/network')
def network():
    ret = []
    cluster_id = request.args.get('cluster_id')

    for n in Network.query.filter_by(cluster_id=cluster_id).all():
        ret.append({'id':n.id, 'name':n.name, 'if_default':n.if_default})

    return json.dumps(ret)


@mod.route('/osimage')
def osimage():
    ret = []
    cluster_id = request.args.get('cluster_id')

    for i in OS_Image.query.filter_by(cluster_id=cluster_id).all():
        ret.append({'id':i.id, 'name':i.name})

    return json.dumps(ret)

app/views/order.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask.ext.wtf import Form, SelectField, TextField, BooleanField, Required, Length
from flask.ext.login import current_user
from flask.ext.paginate import Pagination

from sqlalchemy import distinct

import simplejson as json

from app import app
from app.models import *
from app.dicts import *
from app.views import *
from app.occi import OCCI
from app.order import *
from app.vm import VMC

mod = Blueprint('order', __name__, url_prefix='/order')


@mod.route('/new', methods=['GET', 'POST'])
def new():
    form = OrderForm()
    form.cluster_id.choices = [(i.id, i.name) for i in Cluster.query.all()]
    form.cnt.choices = [(i, i) for i in range(1, 11)]
    cpu = db.session.query(CPU_Mem.cpu.distinct().label('cpu')).order_by(CPU_Mem.cpu).all()

    if not form.validate_on_submit():
        edit = 1 if request.method=='POST' else 0
        return render_template('order/new.html', form=form, cpu=cpu, edit=edit, price=app.config['PRICE'])

    orders = Orders(form.cluster_id.data, form.cpu.data, form.mem.data, form.network.data, form.disk.data, 
                    request.form['os_id'], form.cnt.data, 0, current_user.user_id, form.desc.data, form.days.data)
    db.session.add(orders)
    db.session.commit()

    return redirect(url_for('my_order.list'))


@mod.route('/list', defaults={'page':1})
@mod.route('/list/page/<int:page>')
def list(page, **kvargs):
    order = Orders.query.order_by(Orders.id.desc()).paginate(page, per_page=15, error_out=True)
    return render_template('order/list.html', order=order, order_status=app.config['ORDER_STATUS'])


@mod.route('/<int:order_id>/view')
@check_load_order
def view(order, **kvargs):
    network_dict = network2dict()
    form = OrderForm(obj=order)
    return render_template('order/view.html', order=order, network_dict=network_dict, form=form, config=app.config)


@mod.route('/<int:order_id>/edit', methods=['GET', 'POST'])
@check_load_order
def edit(order, **kvargs):
    order.disk = ','.join(str(x) for x in order.disk)
    order.network = ','.join(str(x) for x in order.network)
    cpu = db.session.query(CPU_Mem.cpu.distinct().label('cpu')).order_by(CPU_Mem.cpu).all()
    form = OrderForm(obj=order)
    form.cluster_id.choices = [(i.id, i.name) for i in Cluster.query.all()]
    form.cnt.choices = [(i, i) for i in range(1, 11)]

    if not form.validate_on_submit():
        return render_template('order/edit.html', form=form, cpu=cpu, order=order, edit=1, price=app.config['PRICE'])

    form.populate_obj(order)
    db.session.add(order)
    db.session.commit()

    return redirect(url_for('my_order.view', order_id=order.id))


@mod.route('/<int:order_id>/delete', methods=['GET', 'POST'])
@check_load_order
def delete(order, **kvargs):
    ret = {}
    vmc = VMC()

    try:
        for x in order.vm:
            vmc.delete(x)
        db.session.delete(order)
        db.session.commit()
        ret['status'] = 1
        ret['msg'] = u"删除成功"
    except:
        ret['status'] = 0
        ret['msg'] = u"删除失败"

    return json.dumps(ret)


@mod.route('/<int:order_id>/approve')
@check_load_order
def approve(order, **kvargs):
    orderc = OrderC(order)
    if orderc.create_vm():
        flash(u'虚拟机创建成功', 'success')
    else:
        flash(u'虚拟机创建失败', 'error')
    return redirect(url_for('.view', order_id=order.id))


@mod.route('/<int:order_id>/cancle')
@check_load_order
def cancle(order, **kvargs):
    orderc = OrderC(order)
    orderc.cancle()
    flash(u'取消申请', '')
    return redirect(request.referrer)


@mod.route('/<int:order_id>/reject')
@check_load_order
def reject(order, **kvargs):
    orderc = OrderC(order)
    orderc.reject()
    return redirect(url_for('.view', order_id=order.id))


@mod.route('/<int:order_id>/refresh')
@check_load_order
def refresh(order, **kvargs):
    vminst = VMC()
    if vminst.refresh():
        flash(u'刷新成功', 'success')
    else:
        flash(u'刷新失败', 'success')
    return redirect(request.referrer)


@mod.route('/<int:order_id>/state_change')
@check_load_order
def state_change(order, **kvargs):
    new_state = request.args.get('state', order.status)
    order.status = new_state
    db.session.add(order)
    db.session.commit()
    return redirect(url_for('.view', order_id=order.id))


class OrderForm(Form):
    desc = TextField(u'用途', validators=[Required(message=u"不能为空")])
    cluster_id = SelectField(u'集群', coerce=int)
    cpu = TextField(u'CPU', validators=[Required()])
    mem = TextField(u'内存', validators=[Required()])
    network = TextField(u'网络', validators=[])
    disk = TextField(u'磁盘', validators=[])
    os_id = TextField(u'操作系统', validators=[Required()])
    cnt = SelectField(u'台数', coerce=int)
    days = TextField(u'天数', validators=[Length(max=30)])

app/templates/order/edit.html
{% extends 'order/layout.html' %}

{% block nav %}
{% from 'import/nav.html' import nav %}
{{ nav(current_user, 'buy') }}
{% endblock %}

{% from 'import/forms.html' import field %}


{% block addon_head %}
<link href="{{ url_for('custom_static', filename='order/form.css') }}" rel="stylesheet">
<script src="{{ url_for('custom_static', filename='order/form.js') }}"></script>
<script type="text/javascript">
    edit = {{ edit }};
    price = {{ price|safe }};
</script>
{% endblock %}


{% block content_body %}
{% from 'order/form.html' import order_form %}
{{ order_form(form, cpu, url_for('order.edit', order_id=order.id), order) }}
{% endblock %}

app/templates/order/form.html
{% from 'import/forms.html' import field %}


{% macro order_form(form, cpu, action, order='') %}
<form class="form-horizontal" method="POST" action="{{ action }}">
    {{ form.hidden_tag() }}
    {{ form.csrf }}

    {{ field(form, 'desc') }}
    {{ field(form, 'cluster_id') }}

    {{ field(form, 'cpu', gclass='hide') }}
    <div class="control-group">
        <label class="control-label">CPU</label>
        <div class="controls">
            {% for c in cpu %}
            <button type="button" class="btn btn-cpu" value="{{ c.cpu }}" data-mem-api="{{ url_for('api.mem_scheme') }}">{{ c.cpu }}核</button>
            {% endfor %}
        </div>
    </div>

    {{ field(form, 'mem', gclass='hide') }}
    <div class="control-group" id="group-mem">
        <label class="control-label">内存</label>
        <div id="mem-template" class="hide">
            <button type="button" class="btn btn-mem" value="{mem}">{mem}G</button>
        </div>
        <div class="controls">
        </div>
    </div>

    {{ field(form, 'network', gclass='hide') }}
    <div class="control-group">
        <label class="control-label">网卡</label>
        <div class="controls pdt-5">
            <div id="nic-label-template" class="hide">
                <span class="label label-info" value="{value}">{label}&nbsp;<a class="close">X</a></span>
            </div>
            <div id="nic-label"></div>
            <select id="nic-template" name="nic-template" class="hide">
                <option value="{value}">{label}</option>
            </select>
            <select id="nic-option" name="nic-option" data-api="{{ url_for('api.network') }}">
            </select>
            <button id="nic-add-btn" type="button" class="btn">添加</button>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label">系统盘</label>
        <div class="controls pdt-5">
            <p>30GB（免费赠送）</p>
        </div>
    </div>

    {{ field(form, 'disk', gclass='hide') }}
    <div class="control-group" id="group-disk">
        <label class="control-label">数据盘</label>
        <div class="controls pdt-5">
            <div id="disk-label-template" class="hide">
                <span class="label label-info" value="{disksize}">{disksize}G&nbsp;&nbsp;<a class="close">X</a></span>
            </div>
            <div id="disk-label"></div>
            <div id="disk-slider" class="pull-left"></div>
            <div class="input-append pull-left" id="disk-input-group">
                <input class="input-mini" id="disk-input" type="text">
                <span class="add-on">GB</span>
            </div>
            <button id="disk-add-btn" type="button" class="btn">添加</button>
        </div>
    </div>

    <div class="control-group group-os">
        <label class="control-label">操作系统</label>
        <div class="controls">
            <input id="osid-pre" type="hidden" value="{{ form.os_id.data }}"/>
            <select id="os-template" name="os-template" class="hide">
                <option value="{value}">{label}</option>
            </select>
            <select id="os_id" name="os_id" data-api="{{ url_for('api.osimage') }}">
            </select>
        </div>
    </div>

    {{ field(form, 'cnt') }}
    {{ field(form, 'days', gclass="hide") }}

    <div class="control-group">
        <label class="control-label">价格</label>
        <div class="controls pdt-5">
            <font color="red"><b id="price"></b>&nbsp;元/月/台</font>
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <button type="submit" class="btn btn-large btn-primary">提交</button>
        </div>
    </div>
</form>
{% endmacro %}

app/templates/order/index.html
{% extends 'order/layout.html' %}

{% from 'import/forms.html' import field %}

{% block addon_head %}
<link href="{{ url_for('custom_static', filename='order/index.css') }}" rel="stylesheet">
<script src="{{ url_for('custom_static', filename='order/index.js') }}"></script>
{% endblock %}

{% block content_body %}
<br/>
<form class="form-horizontal" method="POST" action="{{ url_for('order.new') }}">
    {{ form.hidden_tag() }}
    {{ form.csrf }}

    {{ field(form, 'cluster_id') }}

    {{ field(form, 'cpu', gclass='hide') }}
    <div class="control-group">
        <label class="control-label">CPU</label>
        <div class="controls">
            {% for c in cpu %}
            <button type="button" class="btn btn-cpu" value="{{ c.cpu }}" data-mem-api="{{ url_for('api.mem_scheme') }}">{{ c.cpu }}核</button>
            {% endfor %}
        </div>
    </div>

    {{ field(form, 'mem', gclass='hide') }}
    <div class="control-group" id="group-mem">
        <label class="control-label">内存</label>
        <div id="mem-template" class="hide">
            <button type="button" class="btn btn-mem" value="{mem}">{mem}G</button>
        </div>
        <div class="controls">
        </div>
    </div>

    {{ field(form, 'network', gclass='hide') }}
    <div class="control-group">
        <label class="control-label">网卡</label>
        <div class="controls pdt-5">
            <div id="nic-label-template" class="hide">
                <span class="label label-info" value="{value}">{label}&nbsp;<a class="close">X</a></span>
            </div>
            <div id="nic-label"></div>
            <select id="nic-template" name="nic-template" class="hide">
                <option value="{value}">{label}</option>
            </select>
            <select id="nic-option" name="nic-option" data-api="{{ url_for('api.network') }}">
            </select>
            <button id="nic-add-btn" type="button" class="btn">添加</button>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label">系统盘</label>
        <div class="controls pdt-5">
            <p>30GB（免费赠送）</p>
        </div>
    </div>

    {{ field(form, 'disk', gclass='hide') }}
    <div class="control-group" id="group-disk">
        <label class="control-label">数据盘</label>
        <div class="controls pdt-5">
            <div id="disk-label-template" class="hide">
                <span class="label label-info" value="{disksize}">{disksize}G&nbsp;&nbsp;<a class="close">X</a></span>
            </div>
            <div id="disk-label"></div>
            <div id="disk-slider" class="pull-left"></div>
            <div class="input-append pull-left" id="disk-input-group">
                <input class="input-mini" id="disk-input" type="text">
                <span class="add-on">GB</span>
            </div>
            <button id="disk-add-btn" type="button" class="btn">添加</button>
        </div>
    </div>

    <div class="control-group group-os">
        <label class="control-label">操作系统</label>
        <div class="controls">
            <select id="os-template" name="os-template" class="hide">
                <option value="{value}">{label}</option>
            </select>
            <select id="os-id" name="os-id" data-api="{{ url_for('api.osimage') }}">
            </select>
        </div>
    </div>

    {{ field(form, 'cnt') }}
    {{ field(form, 'desc') }}

    <div class="control-group">
        <label class="control-label">价格</label>
        <div class="controls pdt-5">
            <font id="price" color="red"><b>324</b>&nbsp;元/月</font>
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <button type="submit" class="btn btn-large btn-primary">提交</button>
        </div>
    </div>
</form>
{% endblock %}

app/templates/order/layout.html
{% extends 'layout.html' %}

{% block nav %}
{% from 'import/nav.html' import nav %}
{{ nav(current_user, 'buy') }}
{% endblock %}

app/templates/order/list.html
{% extends 'order/layout.html' %}


{% block addon_head %}
<script src="{{ url_for('custom_static', filename='order/list.js') }}"></script>
{% endblock %}


{% block content_body %}
<table class="table table-hover">
    <thead>
        <tr>
            <th>用途</th>
            <th>集群</th>
            <th>CPU</th>
            <th>内存</th>
            <th>系统</th>
            <th>数量</th>
            <th>状态</th>
            <th>申请时间</th>
            <th>申请人</th>
            <th width="5%">操作</th>
        </tr>
    </thead>
    <tbody>
        {% if order.items.__len__() == 0 %}
        <tr>
            <td colspan="10">Null</td>
        </tr>
        {% else %}
        {% for o in order.items %}
        <tr>
            <td>{{ o.desc }}</td>
            <td>{{ o.cluster.name }}</td>
            <td>{{ o.cpu }}核</td>
            <td>{{ o.mem }}G</td>
            <td>{{ o.os.name }}</td>
            <td>{{ o.cnt }}</td>
            <td><span class="label {{ order_status[o.status].class }}">{{ order_status[o.status].label }}</span></td>
            <td>{{ o.created_time.strftime("%Y-%m-%d %H:%M") }}</td>
            <td>{{ o.user.chinese_name }}</td>
            <td class="action">
               <a class="delete" href="{{ url_for('order.delete', order_id=o.id) }}"><i class="icon-trash"></i></a>
               <a href="{{ url_for('order.view', order_id=o.id) }}"><i class="icon-chevron-right"></i></a>
            </td>
        </tr>
        {% endfor %}
        {% endif %}
    </tbody>
</table>

{% from 'import/pagination.html' import render_pagination %}
{{ render_pagination(order, 'order.list') }}
{% endblock %}

app/templates/order/new.html
{% extends 'order/layout.html' %}

{% block nav %}
{% from 'import/nav.html' import nav %}
{{ nav(current_user, 'buy') }}
{% endblock %}

{% from 'import/forms.html' import field %}


{% block addon_head %}
<link href="{{ url_for('custom_static', filename='order/form.css') }}" rel="stylesheet">
<script src="{{ url_for('custom_static', filename='order/form.js') }}"></script>
<script type="text/javascript">
    edit = {{ edit }};
    price = {{ price|safe }};
</script>
{% endblock %}


{% block content_body %}
{% from 'order/form.html' import order_form %}
{{ order_form(form, cpu, url_for('order.new')) }}
{% endblock %}

app/templates/order/view.html
{% extends 'order/layout.html' %}


{% block addon_head %}
<link href="{{ url_for('custom_static', filename='order/view.css') }}" rel="stylesheet">
<script src="{{ url_for('custom_static', filename='order/view.js') }}"></script>
{% endblock %}

{% from 'order/import/view.html' import order_view %}
{% block content_body %}
{{ order_view(order, network_dict, form, config, current_user) }}
{% endblock %}