app/views/api.py
# -*- coding: utf-8 -*-

from flask import Blueprint, request

import simplejson as json

from app.models import *
from app.views import *

mod = Blueprint('api', __name__, url_prefix='/api')


@mod.route('/cluster/<int:cluster_id>')
@check_load_cluster
def cluster(cluster, **kvargs):
    return '{"cluster_id":%s , "cluster_name":"%s", "if_test":%s}' % \
            (cluster.id, cluster.name, cluster.if_test)


@mod.route('/cpu_scheme')
def cpu_scheme():
    ret = []

    for c in db.session.query(CPU_Mem.cpu.distinct().label('cpu')).order_by(CPU_Mem.cpu).all():
        ret.append(c.cpu)

    return json.dumps(ret)


@mod.route('/mem_scheme')
def mem_scheme():
    ret = []
    cpu = request.args.get('cpu')

    for m in CPU_Mem.query.filter_by(cpu=cpu).order_by(CPU_Mem.mem):
        ret.append(m.mem)

    return json.dumps(ret)


@mod.route('/network')
def network():
    ret = []
    cluster_id = request.args.get('cluster_id')

    for n in Network.query.filter_by(cluster_id=cluster_id).all():
        ret.append({'id':n.id, 'name':n.name, 'if_default':n.if_default})

    return json.dumps(ret)


@mod.route('/osimage')
def osimage():
    ret = []
    cluster_id = request.args.get('cluster_id')

    for i in OS_Image.query.filter_by(cluster_id=cluster_id).all():
        ret.append({'id':i.id, 'name':i.name})

    return json.dumps(ret)

app/views/vm.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, request, redirect, url_for, make_response, jsonify, flash

import simplejson as json

from app import app, db
from app.views import *
from app.utils import *
from app.dicts import *
from app.models import *
from app.vm import VMC
from app.sunstone import Sunstone

mod = Blueprint('vm', __name__, url_prefix='/vm')


@mod.route('/test', defaults={'page':1})
@mod.route('/test/page/<int:page>')
def test(page, **kvargs):
    vms = VM.query.filter(VM.if_test==1).order_by(VM.hostname.asc()).paginate(page, per_page=15, error_out=True)
    return render_template('vm/test.html', vms=vms)


@mod.route('/production', defaults={'page':1})
@mod.route('/production/page/<int:page>')
def production(page, **kvargs):
    vms = VM.query.filter(VM.if_test!=1).order_by(VM.hostname.asc()).paginate(page, per_page=15, error_out=True)
    return render_template('vm/production.html', vms=vms)


@mod.route('/<int:vm_id>/view')
@check_load_vm
def view(vm, **kvargs):
    vminst = VMC()
    vm_detail = vminst.detail(vm)
    network_dict = network2dict()
    cpu = [x.cpu for x in db.session.query(CPU_Mem.cpu.distinct().label('cpu')).order_by(CPU_Mem.cpu).all()]
    mem = CPU_Mem.query.filter(CPU_Mem.cpu==vm.cpu).order_by(CPU_Mem.mem).all()
    return render_template('vm/view.html', vm=vm, cpu=cpu, mem=mem, vm_detail=vm_detail, network_dict=network_dict)


@mod.route('/<int:vm_id>/delete', methods=['POST'])
@check_load_vm
def delete(vm, **kvargs):
    vminst = VMC()
    status = 1 if vminst.delete(vm) else 0
    return jsonify(status=status)


@mod.route('/action', methods=['POST'])
def action_mult():
    status = 1
    vminst = VMC()

    try:
        action = request.form['action']
    except:
        action = None

    if request.form['vmlist'] == "":
        vmlist = []
    else:
        vmlist = request.form['vmlist'].split(',')

    for x in vmlist:
        vm = VM.query.get(int(x))
        if action == 'delete':
            if not vminst.delete(vm):
                status = 0
        if action == 'start':
            if not vminst.start(vm):
                status = 0
        if action == 'poweroff':
            if not vminst.poweroff(vm):
                status = 0
        if action == 'poweroff_hard':
            if not vminst.poweroff_hard(vm):
                status = 0
        if action == 'reboot':
            if not vminst.reboot(vm):
                status = 0
        if action == 'reboot_hard':
            if not vminst.reboot_hard(vm):
                status = 0
        if action == 'recreate':
            if not vminst.recreate(vm):
                status = 0

    vminst.refresh()

    if status:
        flash(u'操作成功', 'success')
    else:
        flash(u'操作失败', 'error')
    return redirect(request.referrer)


@mod.route('/<int:vm_id>/rename', methods=['GET', 'POST'])
@check_load_vm
def rename(vm, **kvargs):
    try:
        newname = request.form['data'] or vm.hostname
        vminst = VMC()
        vminst.rename(vm, newname)
        vm.hostname = newname
        db.session.add(vm)
        db.session.commit()
        status = 1
    except:
        status = 0

    return jsonify(status=status)


@mod.route('/<int:vm_id>/resize', methods=['GET', 'POST'])
@check_load_vm
def resize(vm, **kvargs):
    try:
        vminst = VMC()
        cpu = request.form['cpu'] or vm.cpu
        mem = request.form['mem'] or vm.mem
        vminst.resize(vm, cpu, mem)
        status = 1
    except:
        status = 0

    return jsonify(status=status)


@mod.route('/<int:vm_id>/attach_nic', methods=['GET', 'POST'])
@check_load_vm
def attach_nic(vm, **kvargs):
    #try:
    vminst = VMC()
    network_id = request.form['network_id']
    vminst.attach_nic(vm, network_id)
    flag = True
    sunstone = Sunstone(vm.cluster)
    while flag:
        resp = sunstone.vm_id(vm.vm_id)
        info = json.loads(resp.data)['VM']
        if int(info['STATE']) == 3:
            flag = False
    status = 1
    #except:
    #    status = 0

    return jsonify(status=status)


@mod.route('/<int:vm_id>/detach_nic', methods=['GET', 'POST'])
@check_load_vm
def detach_nic(vm, **kvargs):
    try:
        vminst = VMC()
        nic_id = request.form['nic_id']
        vminst.detach_nic(vm, nic_id)
        flag = True
        sunstone = Sunstone(vm.cluster)
        while flag:
            resp = sunstone.vm_id(vm.vm_id)
            info = json.loads(resp.data)['VM']
            if int(info['STATE']) == 3:
                flag = False
        status = 1
    except:
        status = 0

    return jsonify(status=status)


@mod.route('/<int:vm_id>/redesc', methods=['GET', 'POST'])
@check_load_vm
def redesc(vm, **kvargs):
    try:
        desc = request.form['data'] or vm.desc
        vm.desc = desc
        db.session.add(vm)
        db.session.commit()
        status = 1
    except:
        status = 0

    return jsonify(status=status)


@mod.route('/refresh')
def refresh():
    vminst = VMC()
    if vminst.refresh():
        flash(u'刷新成功', 'success')
    else:
        flash(u'刷新失败', 'error')
    return redirect(request.referrer)

app/templates/vm/layout.html
{% extends 'layout.html' %}


{% block nav %}
{% from 'import/nav.html' import nav %}
{{ nav(current_user, 'machine') }}
{% endblock %}

app/templates/vm/list.html
{% macro vm_list(vms, title, endpoint, current_user, if_test=False, my=False) %}
<div class="content-head">
    <h2 class="pull-left">{{ title }}</h2>
    <div class="pull-right" id="vmop-btn">
        <a href="{{ url_for('vm.refresh') }}" title="刷新" class="btn btn-action refresh"><i class="icon-refresh"></i></a>
        {% if if_test %}
        <a href="#" title="续租" class="btn btn-action "><i class="icon-time"></i></a>
        {% endif %}
        <div class="btn-group">
            <div class="btn-group group-dropdown">
                <a href="#" title="启动" class="btn btn-action start dropdown-toggle"><i class="icon-play"></i></a>
            </div>
            <div class="btn-group group-dropdown">
                <a href="#" title="关机" class="btn btn-action dropdown-toggle" data-toggle="dropdown"><i class="icon-pause"></i>&nbsp;<span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu" id="poweroff">
                    <li><a href="#" class="poweroff"></i>关机</a></li>
                    <li><a href="#" class="poweroff_hard"></i>强制关机</a></li>
                </ul>
            </div>
            <div class="btn-group group-dropdown">
                <a href="#" title="重启" class="btn btn-action dropdown-toggle" data-toggle="dropdown"><i class="icon-repeat"></i>&nbsp;<span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu" id="reboot">
                    <li><a href="#" class="reboot"></i>重启</a></li>
                    <li><a href="#" class="reboot_hard"></i>强制重启</a></li>
                </ul>
            </div>
        </div>
        <div class="btn-group">
            <a href="#" title="重新创建" class="btn btn-action recreate"><i class="icon-retweet"></i></a>
            <a href="#" title="删除" class="btn btn-action delete"><i class="icon-trash"></i></a>
        </div>
    </div>
    <div class="clear"></div>
</div>


<form id="vmop" class="hide" action="{{ url_for('vm.action_mult') }}" method="POST">
    <input type="text" id="vmlist" name="vmlist" value=""/>
    <input type="text" id="action" name="action" value=""/>
</form>

<table class="table table-hover">
    <thead>
        <tr>
            <th width="10"><input type="checkbox"></th>
            <th>机器名</th>
            {% if not my %}
            <th>CPU</th>
            <th>内存</th>
            {% endif %}
            <th>IP</th>
            <th>用途</th>
            <th>状态</th>
            {% if if_test %}
            <th>剩余天数</th>
            {% endif %}
            <th>申请人</th>
            <th>价格</th>
            <th width="40">VNC</th>
        </tr>
    </thead>
    <tbody>
        {% if vms.items.__len__() == 0 %}
        <tr>
            {% if if_test %}
            <td colspan="11">Null</td>
            {% else %}
            <td colspan="10">Null</td>
            {% endif %}
        </tr>
        {% endif %}
        {% for x in vms.items %}
        <tr id="vm_{{ x.id }}" data-id="{{ x.id }}" data-detail="{{ url_for('vm.view', vm_id=x.id) }}">
            <td><input type="checkbox"></td>
            <td class="hostname">
                <span>{{ x.hostname }}</span>
                <input class="input-small hide" value="{{ x.hostname }}"/>
            </td>
            {% if not my %}
            <td>{{ x.cpu }}核</td>
            <td>{{ x.mem }}G</td>
            {% endif %}
            <td>{{ '<br/>'.join(x.ip)|safe }}</td>
            <td>{{ x.desc }}</td>
            <td>{{ x.status }}</td>
            {% if if_test %}
            <td>{{ x.days }}</td>
            {% endif %}
            <td>{{ x.user.chinese_name }}</td>
            <td>{{ x.price }}</td>
            {% if x.status == 'RUNNING' %}
            <td>&nbsp;&nbsp;<a href="#" class="vnc_on"></a></td>
            {% else %}
            <td>&nbsp;&nbsp;<a href="#" class="vnc_off"></a></td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>

{% from 'import/pagination.html' import render_pagination %}
{{ render_pagination(vms, endpoint) }}

<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 id="myModalLabel">Modal header</h4>
    </div>
    <div class="hide" id="tabs_active"></div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
</div>
{% endmacro %}

app/templates/vm/occi_template.html
<COMPUTE>
    <INSTANCE_TYPE>custom</INSTANCE_TYPE>

    <CPU>{{ order.cpu }}</CPU>
    <VCPU>{{ order.cpu }}</VCPU>
    <MEMORY>{{ order.mem * 1024 }}</MEMORY>

    {% for n in order.network  %}
    <NIC>
        <NETWORK href="http://0.0.0.0:4567/network/{{ network_dict[n].sunstone_id }}"/>
        <MODEL>virtio</MODEL>
    </NIC>
    {% endfor %}

    <DISK>
        <STORAGE href="http://0.0.0.0:4567/storage/{{ order.os.sunstone_id }}"/>
        <DEV_PREFIX>vd</DEV_PREFIX>
        <TARGET>vda</TARGET>
        {% if ds_mad == "ceph" %}
        <DRIVER>raw</DRIVER>
        {% elif ds_mad == "fs" %}
        <DRIVER>qcow2</DRIVER>
        {% endif %}
    </DISK>

    {% if ds_mad == "ceph" %}
      {% for d in disk_arr %}
        <DISK>
            <STORAGE href="http://0.0.0.0:4567/storage/{{ d }}"/>
            <DEV_PREFIX>vd</DEV_PREFIX>
            <DRIVER>raw</DRIVER>
        </DISK>
      {% endfor %}
    {% elif ds_mad == "fs" %}
      {% for d in order.disk %}
        <DISK>
            <TYPE>fs</TYPE>
            <SIZE>{{ d * 1024 }}</SIZE>
            <DEV_PREFIX>vd</DEV_PREFIX>
            <FORMAT>raw</FORMAT>
            <DRIVER>raw</DRIVER>
        </DISK>
      {% endfor %}
    {% endif %}

    <OS>
        <ARCH>x86_64</ARCH>
    </OS>

    <GRAPHICS>
        <TYPE>VNC</TYPE>
        <LISTEN>0.0.0.0</LISTEN>
    </GRAPHICS>
</COMPUTE>

app/templates/vm/production.html
{% extends 'vm/layout.html' %}


{% block addon_head %}
<link href="{{ url_for('custom_static', filename='vm/list.css') }}" rel="stylesheet">
<script src="{{ url_for('custom_static', filename='vm/list.js') }}"></script>
<script src="{{ url_for('custom_static', filename='vm/view.js') }}"></script>
{% endblock %}

{% block content_body %}
{% from 'vm/list.html' import vm_list %}
{{ vm_list(vms, "线上机器", 'vm.production', current_user, if_test=False) }}
{% endblock %}

app/templates/vm/test.html
{% extends 'vm/layout.html' %}


{% block addon_head %}
<link href="{{ url_for('custom_static', filename='vm/list.css') }}" rel="stylesheet">
<script src="{{ url_for('custom_static', filename='vm/list.js') }}"></script>
<script src="{{ url_for('custom_static', filename='vm/view.js') }}"></script>
{% endblock %}

{% block content_body %}
{% from 'vm/list.html' import vm_list %}
{{ vm_list(vms, "测试机", 'vm.test', current_user, if_test=True) }}
{% endblock %}

app/templates/vm/view.html
{% macro detail_item(label, value) %}
<tr>
    <td width="30%" class="name">{{ label }}</td>
    <td width="70%">{{ value }}</td>
</tr>
{% endmacro %}

<div class="tabbable">
    <ul class="nav nav-tabs">
        <li class="refresh"><a href="{{ url_for('vm.view', vm_id=vm.id) }}" id="vm_refresh"><i class="icon-refresh"></i></a></li>
        <li class="basic_info active"><a href="#basic_info" data-toggle="tab">基本信息</a></li>
        <li class="monitor"><a href="#monitor" data-toggle="tab">监控</a></li>
        <li class="cpu_mem"><a href="#cpu_mem" data-toggle="tab">CPU/MEM</a></li>
        <li class="nic"><a href="#nic" data-toggle="tab">网卡</a></li>
        <li class="disk"><a href="#disk" data-toggle="tab">磁盘</a></li>
        <li class="snapshot"><a href="#snapshot" data-toggle="tab">快照</a></li>
        <li class="log"><a href="#log" data-toggle="tab">操作日志</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="basic_info">
            <table class="table table-bordered detail">
                <tr>
                    <td class="name">主机名</td>
                    <td id="hostname" class="basic_action">
                        <span>{{ vm.hostname }}</span>
                        <input class="input-small hide" value="{{ vm.hostname }}"/>
                        <a class="edit" href="#"><i class="icon-edit"></i></a>
                        <a class="save hide" href="{{ url_for('vm.rename', vm_id=vm.id) }}"><i class="icon-ok"></i></a>
                        <a class="cancle hide" href="#"><i class="icon-ban-circle"></i></a>
                    </td>
                </tr>
                {{ detail_item("集群", vm.cluster.name) }}
                <tr>
                    <td class="name">用途</td>
                    <td id="usage" class="basic_action">
                        <span>{{ vm.desc }}</span>
                        <input class="hide" value="{{ vm.desc }}"/>
                        <a class="edit" href="#"><i class="icon-edit"></i></a>
                        <a class="save hide" href="{{ url_for('vm.redesc', vm_id=vm.id) }}"><i class="icon-ok"></i></a>
                        <a class="cancle hide" href="#"><i class="icon-ban-circle"></i></a>
                    </td>
                </tr>
                {{ detail_item("CPU", "%s核" % vm.cpu) }}
                {{ detail_item("内存", "%sG" % vm.mem) }}
                <tr>
                    <td class="name">网卡</td>
                    <td>
                        {% for x in vm.network %}
                        <span class="label">{{ network_dict[x].name }}</span>
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <td class="name">磁盘</td>
                    <td>
                        {% for x in vm.disk %}
                        <span class="label">{{ x }}G</span>
                        {% endfor %}
                    </td>
                </tr>
                {{ detail_item("操作系统", vm.order.os.name) }}
                {{ detail_item("状态", vm.status) }}
                {{ detail_item("Owner", vm.user.chinese_name) }}
                {{ detail_item("创建时间", vm.created_time.strftime("%Y-%m-%d %H:%M")) }}
                {{ detail_item("价格", ("<font color='red'>%s</font>元/月" % vm.price)|safe) }}
            </table>
        </div>
        <div class="tab-pane" id="monitor">
        </div>
        <div class="tab-pane" id="cpu_mem">
            <form class="form-inline" id="resize" action="{{ url_for('vm.resize', vm_id=vm.id) }}">
                {% if vm.status != "POWEROFF" %}
                {% set ifavailable = "disabled" %}
                {% else %}
                {% set ifavailable = "" %}
                {% endif %}
                <select {{ ifavailable }} class="input-small" id="cpu_select">
                    {% for x in cpu %}
                    <option value="{{ x }}" {% if x==vm.cpu %}selected{% endif %}>{{ x }}核</option>
                    {% endfor %}
                </select>
                <select {{ ifavailable }} class="input-small" id="mem_select" data-api="{{ url_for('api.mem_scheme') }}">
                    {% for x in mem %}
                    <option value="{{ x.mem }}" {% if x.mem==vm.mem %}selected{% endif %}>{{ x.mem }}G</option>
                    {% endfor %}
                </select>
                <button {{ ifavailable }} type="button" class="btn" id="resize_btn">resize</button>
                {% if vm.status != "POWEROFF" %}
                &nbsp;&nbsp;&nbsp;&nbsp;
                <i>请先将机器关机，使其在POWEROFF状态再Resize</i>
                {% endif %}
            </form>
            <table class="table table-bordered"> 
                <thead>
                    <tr>
                        <th>CPU</th>
                        <th>内存</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ vm.cpu }}核</td>
                        <td>{{ vm.mem }}G</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="tab-pane" id="nic">
            <form class="form-inline" id="nic_attach" action="{{ url_for('vm.attach_nic', vm_id=vm.id) }}">
                {% if vm.status != "RUNNING" %}
                {% set ifavailable = "disabled" %}
                {% else %}
                {% set ifavailable = "" %}
                {% endif %}
                <select {{ ifavailable }} id="nic_select" class="input-medium">
                    {% for x in vm.cluster.network %}
                    <option value="{{ x.id }}">{{ x.name }}</option>
                    {% endfor %}
                </select>
                <button {{ ifavailable }} type="button" class="btn" id="nic_attach_btn">attach</button>
                {% if vm.status != "RUNNING" %}
                &nbsp;&nbsp;&nbsp;&nbsp;
                <i>只有在机器处于RUNNING状态才能添加网卡</i>
                {% endif %}
            </form>
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>IP</th>
                        <th>MAC</th>
                        <th width="100">操作</th>
                    </tr>
                </thead>
                <tbody>
                    {% if vm_detail['NIC'].__len__() == 0 %}
                    <tr>
                        <td colspan="4">Null</td>
                    </tr>
                    {% endif %}
                    {% for x in vm_detail['NIC'] %}
                    <tr>
                        <td>{{ x.NIC_ID }}</td>
                        <td>{{ x.IP }}</td>
                        <td>{{ x.MAC }}</td>
                        <td><a class="nic_detach" href="{{ url_for('vm.detach_nic', vm_id=vm.id) }}" data-nicid="{{ x.NIC_ID }}">Detach</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="tab-pane" id="disk">
            
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Target</th>
                        <th>大小</th>
                        <th width="100">操作</th>
                    </tr>
                </thead>
                <tbody>
                    {% for x in vm_detail['DISK'] %}
                    <tr>
                        <td>{{ x.DISK_ID }}</td>
                        <td>{{ x.TARGET }}</td>
                        <td></td>
                        <td><a href="#">Detach</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="tab-pane" id="snapshot">
        </div>
        <div class="tab-pane" id="log">
        </div>
    </div>
</div>